name: Lint & Format

on:
  push:
    branches: [ "main", "dev", "Feature*" ]
  pull_request:
    branches: [ "main", "dev", "Feature*" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      # ---------- Frontend Lint ----------
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Install frontend deps
        run: npm install --prefix Frontend
        
      - name: Run ESLint
        run: npm run lint --prefix Frontend
        
      - name: Run Tests
        run: npm test -- --watchAll=false --passWithNoTests --prefix Frontend
